### ISSUE TITLE
Mention related work in README

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#16]
e.g.

* https://github.com/crowding/vadr/blob/master/R/bind.R
* https://stackoverflow.com/questions/7519790/assign-multiple-new-variables-on-lhs-in-a-single-line-in-r

You might also want to mention that this operation is commonly known as a destructuring bind.

**Comment by nteetor** [comment]
Thank you for bringing vadr (and its offshoots) to my attention. I will add a related works section to the README. 

re: destructuring bind, the [vignette](https://github.com/nteetor/zeallot/blob/master/vignettes/unpacking-assignment.Rmd) mentions destructing assignment, but I would have sworn the README referred to destructuring assignment at one point. Sadly I would be wrong. I did a quick poke around the web and my conclusion is destructuring bind and destructuring assignment are synonymous. Is this correct? If so, I will update the repo tags and README.

re: SO post, thank you, I will add an answer suggesting zeallot. I can also update the README with a section about interest(?) or discussions of multiple|unpacking|destructuring assignment.
