### ISSUE TITLE
"Pronouns" for swallowing unneeded arguments

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#18]
Maybe something like this:

```R
{x : ... : y } %<-% list(1, 2, 3, 4, 5)
{x : . : y : . : z} %<-% list(1, 2, 3, 4, 5)
```

**Comment by nteetor** [comment]
The latter syntax is supported.
```R
{x : . : y : . : z} %<-% list(1, 2, 3, 4, 5)
```
In this case, `x`, `y`, and `z` are assigned 1, 3, and 5, respectively. 

Regarding the former syntax, we currently recommend using `....` to swallow unneeded arguments. In this case, `.` *is* assigned the grouped arguments, however this could be changed. What is the case against assigning grouped values and then ignoring the assigned variable?
