### ISSUE TITLE
Some mistakes don't throw errors

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#20]
e.g.

``` r
library(zeallot)

{1} %<-% list(1)
{f()} %<-% list(1)
```

**Comment by nteetor** [comment]
`{1} %<-% list(1)` is questionably valid since `` `1` <- 1 `` is a valid R expression.

The behaviour of your second example is not intended and I will look into it, thank you for bringing the problem to my attention.

**Comment by hadley** [comment]
But `1 <- 1` is not. I don't think zeallot syntax implies automatic quoting of the LHS.

**Comment by nteetor** [comment]
Correct, there is no mention of automatic quoting of the LHS. This can be addressed (the error message, not automatic quoting).

**Comment by nteetor** [comment]
Note to self, be sure to address this issue when working through syntax conversion #21
