### ISSUE TITLE
Alternative syntax?

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#21]
I think `c(a, b, c) <- f()` would be a nice alternative to `{a : b : c} <- f()`.

**Comment by nteetor** [comment]
The original zeallot, named allotalot at the time, syntax used a `.()` helper function to construct the LHS of an assignment expression.
```R
.(a, b, c) %<-% f()
```
With that syntax the `%<-%` could be dropped and similar to vadr's bind functionality `<-` could be used instead.

I am wary of overwriting `<-` or `c()`. However, I do agree a simpler syntax would be nice.

**Comment by hadley** [comment]
Oops, I meant ` c(a, b, c) %<-% f()`

**Comment by nteetor** [comment]
Yes, I don't see why that wouldn't be possible.

Would the nested syntax look as follows,
`c(a, c(b, d), e) %<-% f()`

**Comment by jimhester** [comment]
FWIW I don't think need to overwrite `c()` since you never actually evaluate the lhs.

**Comment by nteetor** [comment]
Yep, I agree. The overwriting was brought up, but is no longer relevant because of @hadley 's correction to the proposed alternative syntax.

**Comment by nteetor** [comment]
@jimhester, you have me thinking though, is there a reason why a `` `c<-`() `` function couldn't be implemented? Upon first consideration this seems like a way around overwriting `<-` and defining the custom `%<-%`.

**Comment by nteetor** [comment]
With some further fiddling I see there are plenty of hurdles along the `` `c<-`() `` route, if it's possible at all. Proceeding with `%<-%`.

**Comment by jimhester** [comment]
I similar idea is https://github.com/crowding/vadr/blob/master/R/bind.R#L65. Which has the advantage of not requiring an redefinition of `<-`, but the drawback of requiring an object to dispatch on. Using that approach you could have syntax like

```r
.[x, y] <- c(1, 2)
```

**Comment by nteetor** [comment]
I became aware of vadr this morning when hadley brought it to my attention. I see now in the comments of bind.R, crowding was talking about how `` `bind<-` `` would mangel the call, so he settled for `[<-.bind`. 

I like avoiding a different assignment operator. Unfortunately, nesting variables with `.[` feels a little nutty. I would imagine it looks something like this.
```R
.[w, .[x, y], z] <- list(1, list(2, 3), 4)
```

**Comment by nteetor** [comment]
New syntax is ready for submission to CRAN, any further suggestions? I feel good about the new, lighter syntax.
