### ISSUE TITLE
%<=%

### ISSUE THREAD

**Issue by egnha** [nteetor/zeallot#29]
A thought: Instead of `%<-%`, how about `%<=%`?

Advantages:
- the two strokes in `=` (versus single stroke in `-`) visually reflects the notion of multiple (versus single) assignment
- won't conflict with the implicit-future construct in the [future](https://github.com/HenrikBengtsson/future) package

(Could `%<=%` introduce a worse clash than that with `` future::`%<-%` ``?)

**Comment by nteetor** [comment]
Yes, the conflict is one I am aware of. Unfortunately, future used to use `%<=%` and then in March (of 2017) switched to `%<-%`. 

I take it you use both packages?

**Comment by egnha** [comment]
I wouldn't be surprised if some other package in (somewhat) common use might also be using `%<-%`, so perhaps trying to avoid symbol clash is a losing cause ... :/

Is the first "advantage" sufficiently compelling on its own?

**Comment by nteetor** [comment]
The first point doesn't not make sense to me. However, the multiple assignment operator would ideally stand in for the standard operator and the `%<-%` design best indicates this.

**Comment by egnha** [comment]
Maybe I wasn't clear. What I meant: view `<=` as a pictograph for two arrows (⇇), instead of one. (rlang’s unsplicing notation, `!!!`, employs an analogous pictographic association: the dots at the bottom reminds one of `...`.)

**Comment by nteetor** [comment]
No, I understood the double arrow, hence my comment that the point doesn't not make sense. The double arrow implies multiple assignment is not out of left field, but my double negative may have done me a disservice. My preference is to keep the operator as is since most languages use the same operator for standard and multiple assignment.
