### ISSUE TITLE
Assign to existing lists?

### ISSUE THREAD

**Issue by rafaqz** [nteetor/zeallot#32]
Great package, I've missed this a lot after python/haskell.

Just tried something crazy and found it didn't work:

l <- some_existing_list
c(l$a, l$b, l$c) %<-% some_func(x, y)

But it would be nice to be able to assign to absolutely anything on the left hand side without using intermediary variables, no idea how hard that is to implement!

**Comment by nteetor** [comment]
Hello @rafaqz, assigning to nearly anything on the left-hand side sounds possible. I will create a branch and let you know when it is testable. Thank you for the feedback and the suggestion.

**Comment by nteetor** [comment]
Hello again, feel free to check out the [assign-anything](https://github.com/nteetor/zeallot/tree/assign-anything) branch. If everything checks out then I can resubmit to CRAN in about a month.

**Comment by nteetor** [comment]
See release [v0.0.6](https://github.com/nteetor/zeallot/releases/tag/v0.0.6)
