### ISSUE TITLE
Formally support and test R 3.1 and greater?

### ISSUE THREAD

**Issue by hadley** [nteetor/zeallot#40]
This basically just requires adding this to your travis:

```R
r:
- 3.1
- 3.2
- oldrel
- release
- devel
```

And this to `DESCRIPTION`:

```R
Depends:
    R (>= 3.1)
```

And then fixing any small issues that arise.

Then I would feel confident about re-exporting `%<-%` from purrr.

**Comment by nteetor** [comment]
The master branch now is good to go for R 3.1. 

Unfortunately I released zeallot 0.1.0 to CRAN only a week and a half ago. I have gotten colorful replies in the past when releasing quick updates to CRAN. When would you like/need to release the next version of purrr? I will do what I can to make sure the updated zeallot is on CRAN by then. 

Additionally, would it be helpful to put together a PR for purrr? What's your vision for purrr + `%<-%`? If safe functions are the prominent use case there may already be enough examples and documentation. Alternatively, I could explore and put together further examples of using purrr and zeallot.
