### ISSUE TITLE
Assign multiple types?

### ISSUE THREAD

**Issue by brooklynbagel** [nteetor/zeallot#41]
####Neither the README nor unpacking assignment vignette make it explicit you can use `%<-%` to assign different types in one expression. I ran the following experiment and it appears to be the case.

```r
library(zeallot)

c(a, b, c, d, e) %<-% list(1.0, 1L, "1", factor(1), data.frame(x = 1))
lapply(list(a = a, b = b, c = c, d = d, e = e), class)
#> $a
#> [1] "numeric"
#> 
#> $b
#> [1] "integer"
#> 
#> $c
#> [1] "character"
#> 
#> $d
#> [1] "factor"
#> 
#> $e
#> [1]  #"data.frame"
```

Is this expected behavior for how `%<-%` operates? If so, it should be made more clear.

**Comment by nteetor** [comment]
Are you concerned the behavior of the operator will change?
