### ISSUE TITLE
Can we get %<->%?

### ISSUE THREAD

**Issue by t-kalinowski** [nteetor/zeallot#42]
What do you think of an operator that's a combination of ```magritter::`%<>%` ``` and ``` zeallot::`%<-%` ``` 

example usage might be
```
x <- letters[1:4]
y <-  c("w", "x", "y", "z")
f <- c(1,1,2,2)

c(x, y) %<->% lapply(z, function(z) split(z, f))
```
I'm imagining that the operator would take the left hand side  `c(x,y)` and behind the scenes would call `list(x = x, y = y)` and pass that list as the first argument to the right hand side function as `.`, with standard magrittr rules for `.` placement and evaluation.

**Comment by nteetor** [comment]
I am reluctant to introduce such an operator. The operator would add an unnecessary layer of complexity and the resulting expressions would be harder for users to digest. That said, I appreciate you pushing the boundaries and testing waters. In the end we'll have a more concrete definition of the zeallot operators as the grey areas are explored.
