### ISSUE TITLE
!!! tidy eval in LHS of %<-% ?

### ISSUE THREAD

**Issue by t-kalinowski** [nteetor/zeallot#44]
Something like this:

```
assign all dataframe column as variables to the current environment
c(!!! names(mtcars)) %<-% mtcars
```

**Comment by nteetor** [comment]
For this particular example I would strongly encourage using https://github.com/r-lib/withr.

However, the overarching idea is quite interesting. Introducing more symbols into the left-hand side should not be taken lightly, but exploration is in order.
