### ISSUE TITLE
Working in a for loop

### ISSUE THREAD

**Issue by t-kalinowski** [nteetor/zeallot#45]
It would be nice to get multi assign in for loops also (similar to tuple unpacking in python). Here is a mockup implementation. The syntax of this is kinda clunky, it would be nicer if it better mirrored the semantics of an actual R `for` loop, but that will require greater R jedi skills than I currently posses. 

``` r
library(zeallot)
pfor <- function(loop_construct, expr) {
  loop_construct <- substitute(loop_construct)
  expr <- substitute(expr)
  loop_list <- eval(loop_construct[[3]], parent.frame())
  for(i in seq_along(loop_list)) {
    loop_construct[[3]] <- loop_list[[i]]
    eval(loop_construct, envir = parent.frame())
    eval(expr, envir = parent.frame())
  }
}

pfor (c(a, b) %<-% list(list(1, 2), list(3, 4)),
  print(c(a, b)))
#> [1] 1 2
#> [1] 3 4
```

Created on 2018-02-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by t-kalinowski** [comment]
This would be particularly nice with some helpers that provide similar semantics to `purrr::imap()` or to `enumerate()` in python.
``` r

library(zeallot)
library(purrr)
library(glue)

pfor <- function(loop_construct, expr) {
  loop_construct <- substitute(loop_construct)
  expr <- substitute(expr)
  loop_list <- eval(loop_construct[[3]], parent.frame())
  for(i in seq_along(loop_list)) {
    loop_construct[[3]] <- loop_list[[i]]
    eval(loop_construct, envir = parent.frame())
    eval(expr, envir = parent.frame())
  }
}

enumerate <- function(l) {
  if(is.null(names(l)))
    idx <- seq_along(l) 
  else
    idx <- names(l)
  
  transpose(list(idx, l))
}


l <- list(x = 1:3, y = 4:6, z = 7:9)

pfor(c(name, val) %<-% enumerate(l), {
  cat(glue("name: {name}  val: {collapse(val, sep = ', ')}"), "\n")
})
#> name: x  val: 1, 2, 3 
#> name: y  val: 4, 5, 6 
#> name: z  val: 7, 8, 9


names(l) <- NULL

pfor(c(name, val) %<-% enumerate(l), {
  cat(glue("name: {name}  val: {collapse(val, sep = ', ')}"), "\n")
})
#> name: 1  val: 1, 2, 3 
#> name: 2  val: 4, 5, 6 
#> name: 3  val: 7, 8, 9
```

Created on 2018-02-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nteetor** [comment]
This would be awesome. For the time being I would urge users to work with `purrr::map2` or `purrr::pmap`. Because in an ideal world zeallot would not exist. Unpacking and destructuring assignment would be native to R. `purrr`'s toolkit is well suited for the cases described above and the resulting code, in my opinion, would be cleaner. For now I will shelve this idea, but I am right there with you wishing this were a reality.
