### ISSUE TITLE
A named unpacking function sans %->%?

### ISSUE THREAD

**Issue by daranzolin** [nteetor/zeallot#48]
I really like this example from the vignette:

```
mtcars %>%
  subset(hp > 100) %>%
  aggregate(. ~ cyl, data = ., FUN = . %>% mean() %>% round(2)) %>%
  transform(kpl = mpg %>% multiply_by(0.4251)) %->% 
  c(cyl, mpg, ...rest)
```

But I think it would be cool, readable, and writable if we could do something like this:

```
mtcars %>%
  subset(hp > 100) %>%
  aggregate(. ~ cyl, data = ., FUN = . %>% mean() %>% round(2)) %>%
  transform(kpl = mpg %>% multiply_by(0.4251)) %>% 
  unpack(cyl, mpg, ...rest)
```

**Comment by RobertMyles** [comment]
`unpack()` is **much** easier on the eye (love the functinality of  `%->%` btw).

**Comment by traversc** [comment]
I've been looking for something like this because of the conflict with `future` package.  If you look at the `%<-%` definition, there's a hint of how to do this, but I haven't got it exactly right.  Here's what I have so far:

```
library(dplyr)
library(zeallot)
unpack <- function(value, x) {
  zeallot:::multi_assign(substitute(x), value, parent.frame())
}

# works
unpack(c(1,2), c(a,b))
print(a); print(b); rm(a,b)
[1] 1
[1] 2

# doesn't work
c(1,2) %>% unpack(c(a,b))
print(a); print(b); rm(a,b)
Error in print(a) : object 'a' not found
```
I think there's an issue with environment/scope but cant quite figure it out.  Does anyone have any ideas?

**Comment by daranzolin** [comment]
I toyed with something like this with [my kapow package.](https://github.com/daranzolin/kapow)

This works:
```
library(kapow) #devtools::install_github("daranzolin/kapow")
c(a = 1, b = 2) %>% kapow(a, b)
print(a)
[1] 1
print(b)
[1] 2
```

**Comment by traversc** [comment]
That's great -- it would be nice if we could do without the named variables in the input, e.g.:

`list(1,2) %>% kapow(a,b)`

**Comment by nteetor** [comment]
Such a tool is a reasonable request. However, I favor and encourage explicit assignment. Usage of the `%<-%` operator already obfuscates assignment more than I would prefer. I appreciate the interest shown and apologize for half a years worth of silence.
