### ISSUE TITLE
Set := to %<-%

### ISSUE THREAD

**Issue by seasmith** [nteetor/zeallot#50]
Example

```r
`:=` <- zeallot::`%<-%`

c(a, b) := c("this", "that")

a
# [1] "this"
b
# [1] "that"
```

There is no right-hand equivalent, but the `:=` is a valid infix operator and would save a bit of typing.  As an example, packages [rlang](https://github.com/r-lib/rlang/blob/master/NAMESPACE#L64) and [data.table](https://github.com/Rdatatable/data.table/blob/master/NAMESPACE#L14) export their own defined `:=` infix operator.

**Comment by nteetor** [comment]
This is a great suggestion and I would encourage anyone who likes the idea to amend their `.Rprofile` file. At this time I do not plan to include an alternate operator. Because the multiple assignment syntax is non-standard including yet another syntax would further obfuscate code. I appreciate the input and I hope {zeallot} has proved useful for you.

**Comment by seasmith** [comment]
{zeallot} is an extraordinary package, which is why it deserves extraordinary syntax.  

`:=` evokes assignment while  `%<-%` becomes mistaken for `%>%`.  

```r
library(zeallot)
library(magrittr)
`:=` <- zeallot::`%<-%`

c(setosa, versicolor) := iris %>%
    .[.$Species != "virginica", ] %>%
    split(.$Species, drop = TRUE) %>%
    lapply(function (x) colMeans(x[, -5]))
```

This syntax enhances the user experience by separating the two `%`-wrapped infix operators.  I have added ``` `:=` <- zeallot::`%<-%` ``` to my own personal package though I hope in the future it becomes a {zeallot} standard.

**Comment by nteetor** [comment]
There's a similar problem with `if` statement conditionals. The person reading the code needs to be careful if `<` or `>` are used. The two symbols are similar, but a small difference results in a big change. 

I am glad you have a workaround for using `:=`. R has a lot of flexibility and I love the language for it. At this time I will close this issue. If come across a bug with the syntax feel free to reopen this issue or open a new one.
