### ISSUE TITLE
Support for partial assignment

### ISSUE THREAD

**Issue by chrsigg** [nteetor/zeallot#51]
`list` from the `gsubfn` [package](https://cran.r-project.org/web/packages/gsubfn/index.html) supports assigning only some return values while dropping others:

    # assign Green and Blue (but not Red) components
    list[ , Green, Blue]  <- col2rgb("aquamarine")

Can such functionality be implemented in `zeallot` as well?

As a work-around, I can assign unused return arguments to dummy variables. But as direct assignment of multiple return values is syntactic sugar, I would prefer as sweet a syntax as possible for the price of non-standard assignment and the extra package dependency.

Regards
Christian

**Comment by nteetor** [comment]
Hello Christian, you may be looking for the `.` and `...` shorthands. Using `.` and `...` one can skip a value or values, respectively. 

```R
c(var1, ...) %<-% 1:5
```

```R
c(., var2, ., var4, .) %<-% 1:5
```

Does this help?

**Comment by chrsigg** [comment]
Perfect, and sorry for the noise. I don't know how I missed that in the documentation

**Comment by nteetor** [comment]
No apology necessary, I'm glad you found the answer in the end.
